# Generated by Django 5.0.4 on 2024-04-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('Fase', models.IntegerField(default=1, verbose_name='fase corrente em execução')),
                ('Duracao', models.IntegerField(default=40, verbose_name='número de dias do jogo')),
                ('PrecoCompra', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='preço de compra')),
                ('PrecoVenda', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='preço de venda')),
                ('CustoFixoDiario', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='custo fixo diario')),
                ('CustoUnitarioFrete', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='custo unitario frete')),
                ('CustoUnitarioEstocar', models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='custo unitario de estocar')),
                ('GanhoUnitario', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='ganho unitario')),
                ('DemandaMediaDiária', models.DecimalField(decimal_places=2, default=36, max_digits=5, verbose_name='demanda media diária')),
                ('DiasNoAno', models.IntegerField(default=360, verbose_name='número de dias no ano')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.IntegerField()),
                ('PrazoSorteado', models.IntegerField(verbose_name='prazo sorteado')),
                ('DemandaSorteada', models.IntegerField(verbose_name='demanda Sorteada')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField(default=0, verbose_name='número do grupo')),
                ('Nome', models.CharField(max_length=20, unique=True)),
                ('Quando', models.TextField(blank=True, max_length=800)),
                ('Quanto', models.TextField(blank=True, max_length=800)),
                ('Fase1Ok', models.BooleanField(default=False, verbose_name='grupo decidiu método de gestão')),
                ('Ativo', models.BooleanField(verbose_name='haverá este grupo no jogo')),
                ('GrupoOperador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadorGrupo', to='jogovarejo.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaCompra', models.IntegerField(verbose_name='dia da compra')),
                ('DiaEntrega', models.IntegerField(verbose_name='dia da entrega')),
                ('QuantCompra', models.IntegerField(verbose_name='quantidade comprada')),
                ('HouveFalta', models.BooleanField(null=True, verbose_name='ocorreu falta')),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupoCompra', to='jogovarejo.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.IntegerField()),
                ('Recebido', models.IntegerField(verbose_name='quantidade recebida')),
                ('AReceber', models.IntegerField(verbose_name='quantidade a receber')),
                ('SaldoInicial', models.IntegerField(verbose_name='saldo inicial')),
                ('Comprado', models.IntegerField(null=True, verbose_name='quantidade comprada')),
                ('Prazo', models.IntegerField(null=True, verbose_name='prazo de entrega')),
                ('Demanda', models.IntegerField(null=True, verbose_name='quantidade demandada')),
                ('Vendido', models.IntegerField(null=True, verbose_name='quantidade vendida')),
                ('SaldoFinal', models.IntegerField(null=True, verbose_name='saldo final')),
                ('SaldoMedioDia', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='saldo médio')),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupoMovimento', to='jogovarejo.grupo')),
            ],
        ),
    ]
