# Generated by Django 5.0.4 on 2024-04-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogovarejo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controle',
            old_name='nome',
            new_name='Nome',
        ),
    ]
