# Generated by Django 5.0.4 on 2024-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogovarejo', '0002_rename_nome_controle_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='Fase2Ok',
            field=models.BooleanField(default=False, verbose_name='grupo decidiu método de gestão'),
        ),
    ]
