# Generated by Django 5.0.4 on 2024-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogovarejo', '0003_grupo_fase2ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresDoGrupo',
            fields=[
            ],
            options={
                'verbose_name': 'indicadores de resultado do grupo',
                'verbose_name_plural': 'indicadores de resultado dos grupos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jogovarejo.grupo',),
        ),
        migrations.RemoveField(
            model_name='compra',
            name='HouveFalta',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='Fase2Ok',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='Ativo',
            field=models.BooleanField(verbose_name='está participando do jogo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='Fase1Ok',
            field=models.BooleanField(default=False, verbose_name='decidiu método de gestão'),
        ),
    ]
